// 100 norske suksesshistorier. "navn" er på formen DB-en bruker (fornavn +
// etternavn, store/små bokstaver spiller ingen rolle ved oppslag). "story" er
// en kort, faktabasert oppsummering fra offentlig kjent informasjon – den
// konkrete selskapsstrukturen hentes live fra databasen (roller, aksjeposter,
// skatteliste) når man åpner personen.

export type Suksesshistorie = {
  navn: string;
  fodselsaar: number | null;
  bransje: string;
  story: string;
};

export const suksesshistorier: Suksesshistorie[] = [
  { navn: "Torstein Hagen", fodselsaar: 1943, bransje: "Cruise / shipping / reiseliv",
    story: "Grunnla Viking Cruises i 1997 og bygde det til verdens ledende elve- og ekspedisjonscruise-rederi. Bakgrunn fra McKinsey og shipping; satset på et voksent, velstående marked uten barn og kasino om bord, og tok selskapet på børs i New York i 2024." },
  { navn: "John Fredriksen", fodselsaar: 1944, bransje: "Shipping / investering",
    story: "Startet som oljetanker-megler på 1960–70-tallet og ble verdens største tankreder gjennom Frontline. Bygde et imperium innen tank, tørrlast (Golden Ocean), oppdrett (Mowi), oljeservice (Seadrill) og borerigger. Flyttet til Kypros/London; kjent for aggressiv, syklisk timing i shipping." },
  { navn: "Ole Andreas Halvorsen", fodselsaar: 1961, bransje: "Hedgefond / finans",
    story: "Norsk-amerikansk hedgefondforvalter, en av «Tiger Cubs» fra Julian Robertsons Tiger Management. Medgrunnla Viking Global Investors i 1999, et av verdens største og mest respekterte hedgefond. Mesteparten av formuen er bygd i USA." },
  { navn: "Kjell Inge Røkke", fodselsaar: 1958, bransje: "Industri / fiskeri / investering",
    story: "Begynte som fisker i USA, kjøpte sin første tråler og bygde fiskeriselskapet RGI. Tok kontroll over Aker og Kværner og samlet eierskapet i Aker ASA – med interesser i oljeservice, fornybar energi, sjømat (Aker BioMarine) og industri. Klassisk industribygger med høy gjeldsvilje og langsiktige posisjoner." },
  { navn: "Ivar Tollefsen", fodselsaar: 1961, bransje: "Eiendom",
    story: "Bygde boligeiendomskonsernet Heimstaden fra én gård i Oslo til en av Europas største private utleieaktører, med hundretusenvis av boliger i Norden og Europa. Eier via Fredensborg; kjent for å belåne og kjøpe boligporteføljer i stor skala." },
  { navn: "Petter Stordalen", fodselsaar: 1962, bransje: "Hotell / eiendom / reiseliv",
    story: "Startet som markedssjef og kjøpmann, bygde hotellkjeden Nordic Choice (nå Strawberry) til en av Nordens største. Kombinerer hotell, eiendom og handel via Strawberry-konsernet; kjent som karismatisk selger og merkevarebygger." },
  { navn: "Odd Reitan", fodselsaar: 1951, bransje: "Dagligvare / handel",
    story: "Åpnet sin første dagligvarebutikk i Trondheim og bygde lavpriskjeden Rema 1000 på franchise-modellen. Reitangruppen omfatter i dag dagligvare, servicehandel (Narvesen, 7-Eleven), drivstoff (Uno-X) og eiendom, med virksomhet i flere land." },
  { navn: "Øystein Stray Spetalen", fodselsaar: 1962, bransje: "Investering / finans",
    story: "Aktiv investor og industriell eier kjent for konsentrerte posisjoner og aktivt eierskap i børsnoterte selskaper. Opererer via Ferncliff-systemet med interesser i blant annet industri, shipping og finans; kjent for tydelige markedssyn." },
  { navn: "Nicolai Tangen", fodselsaar: 1966, bransje: "Kapitalforvaltning / finans",
    story: "Grunnla det London-baserte fondsforvaltningsselskapet AKO Capital, som ga ham formuen. Siden 2020 sjef for Norges Bank Investment Management (Oljefondet). Har gitt bort store deler av formuen til allmennyttige formål." },
  { navn: "Svein Støle", fodselsaar: 1963, bransje: "Finans / meglerhus",
    story: "Grunnla og eier meglerhuset og investeringsbanken Pareto, en av Norges ledende uavhengige finanshus innen megling, kapitalforvaltning og prosjektfinansiering, særlig mot shipping, eiendom og energi." },
  { navn: "Jan Petter Collier", fodselsaar: 1950, bransje: "Finans / meglerhus",
    story: "Medgrunnlegger av ABG Sundal Collier, et ledende nordisk investeringsbank- og meglerhus. Bygde formue på corporate finance og aksjehandel i en lang periode med vekst i norsk kapitalmarked." },
  { navn: "Trygve Hegnar", fodselsaar: 1943, bransje: "Media / finans / investering",
    story: "Bygde mediehuset Hegnar Media (Finansavisen, Kapital) og er aktiv investor. Kombinerer redaktørrollen med eierskap i blant annet hotell og industri; kjent profil i norsk nærings- og medieliv." },
  { navn: "Christian Sinding", fodselsaar: 1972, bransje: "Private equity",
    story: "Toppsjef i og partner av EQT, et av Europas største private equity-selskaper med svensk-nordisk opphav. Formuen er bygd gjennom carry og eierandeler i PE-virksomheten." },
  { navn: "Ole Ertvaag", fodselsaar: 1963, bransje: "Private equity / energi",
    story: "Grunnla private equity-selskapet HitecVision i Stavanger, en ledende investor i olje, gass og energiomstilling på norsk sokkel. Bygde formue på oppkjøp og utvikling av energiselskaper." },
  { navn: "Bjørn Rune Gjelsten", fodselsaar: 1956, bransje: "Fiskeri / shipping / investering",
    story: "Investor og industribygger, lenge partner med Røkke i Aker-systemet. Opererer via Gjelsten Holding med interesser i eiendom, industri, shipping og sport; tidligere eier av Wimbledon FC/MK Dons." },
  { navn: "Arne Blystad", fodselsaar: 1955, bransje: "Shipping / investering",
    story: "Shippinginvestor som via Blystad-gruppen har bygd og handlet posisjoner i tank, gass og tørrlast, samt biotek og finans. Kjent for syklisk shipping-timing og aktivt eierskap." },
  { navn: "Tor Olav Trøim", fodselsaar: 1963, bransje: "Shipping / energi / investering",
    story: "Lenge Fredriksens nære medspiller og arkitekt bak flere børsnoteringer (Seadrill, Golar m.fl.). Driver i dag eget investeringsmiljø Magni/ Borr Drilling med vekt på offshore, energi og shipping." },
  { navn: "Arne Fredly", fodselsaar: 1964, bransje: "Investor / trading",
    story: "Selvstendig investor og trader kjent for konsentrerte, ofte motsykliske posisjoner i børsnoterte selskaper innen eiendom, shipping og industri. Bygde formuen på egenhandel og aktivt eierskap." },
  { navn: "Ketil Skorstad", fodselsaar: 1967, bransje: "Investering / finans",
    story: "Medgrunnlegger av forvaltningsmiljøet Tigerstaden/Sector og senere familiekontoret Tudor; har bygd formue på kapitalforvaltning og egne investeringer i blant annet eiendom og børsnoterte aksjer." },
  { navn: "Tore Aksel Voldberg", fodselsaar: 1963, bransje: "Investering / finans",
    story: "Profesjonell investor og trader som har bygd formue på langsiktig egenhandel i aksjemarkedet, ofte med lav profil og konsentrerte posisjoner." },
  { navn: "Jens Ulltveit-Moe", fodselsaar: 1942, bransje: "Industri / energi",
    story: "Bygde industrikonglomeratet Umoe med virksomhet innen oljeservice, fornybar energi, restaurant (bl.a. via investeringer) og industri. Tidligere NHO-president; markant industribygger frem til sin død i 2023." },
  { navn: "Harald Espedal", fodselsaar: 1972, bransje: "Investering / finans",
    story: "Tidligere sjef i Skagenfondene, nå selvstendig investor via Espedal & Co og Salt Value. Bygde formue på fondsforvaltning og egne investeringer, særlig verdiorienterte aksjeposisjoner." },
  { navn: "Kristian Falnes", fodselsaar: 1965, bransje: "Investering / finans",
    story: "Legendarisk forvalter fra Skagenfondene, kjent for langsiktig verdiinvestering. Forvalter i dag egen kapital og investerer i børsnoterte selskaper." },
  { navn: "Anders Onarheim", fodselsaar: 1959, bransje: "Finans / investering",
    story: "Investor og styreprofesjonell med bakgrunn fra meglerhus (bl.a. Carnegie). Aktiv eier og styremedlem i en rekke selskaper innen finans, shipping og industri." },
  { navn: "Jostein Eikeland", fodselsaar: 1967, bransje: "Energi / investering",
    story: "Serieentreprenør innen teknologi og energi, blant annet kjent for batteriselskapet Alevo (som senere gikk konkurs) og senere energiinvesteringer. Kjent for høyrisiko-satsinger." },
  { navn: "Morten Klein", fodselsaar: 1968, bransje: "Gaming / investering",
    story: "Investor med tyngde i spill- og gamingselskaper (bl.a. iGaming) samt børsnoterte vekstselskaper. Bygde formue på tidlige posisjoner i gaming og aktiv handel." },
  { navn: "Jan Haudemann-Andersen", fodselsaar: 1958, bransje: "Investering / finans",
    story: "Investor via Datum-systemet, kjent for tidlige og konsentrerte posisjoner i teknologi- og vekstselskaper på Oslo Børs. Bygde formue på langsiktig aksjeinvestering." },
  { navn: "Olav Nils Sunde", fodselsaar: 1951, bransje: "Shipping / reiseliv / investering",
    story: "Bygde O.N. Sunde-konsernet med interesser i shipping (bl.a. bilfrakt), handel (tidligere eier av Voice/ retail) og eiendom. Bredt diversifisert familieeid konsern." },
  { navn: "Arthur Buchardt", fodselsaar: 1948, bransje: "Hotell / eiendom",
    story: "Eiendoms- og hotellutvikler bak en rekke prosjekter i Norden, blant annet hoteller og næringsbygg. Kjent prosjektmaker med bakgrunn fra entreprenørbransjen." },
  { navn: "Torstein Tvenge", fodselsaar: 1952, bransje: "Eiendom",
    story: "Eiendomsinvestor og aksjeinvestor som har bygd betydelig formue på næringseiendom og langsiktige børsposisjoner, ofte med lav profil." },
  { navn: "Ivar Koteng", fodselsaar: 1959, bransje: "Eiendom",
    story: "Trondheimsbasert eiendomsinvestor, kjent også som tidligere styreleder og eier i Rosenborg Ballklub. Bygde formue på næringseiendom i Trøndelag." },
  { navn: "Edgar Haugen", fodselsaar: null, bransje: "Eiendom / investering",
    story: "Eiendomsinvestor via Ragde Eiendom med en stor portefølje av nærings- og boligeiendom i Oslo-området. Bygde formuen gjennom oppkjøp og utvikling av eiendom." },
  { navn: "Kjetil Strand", fodselsaar: null, bransje: "Eiendom",
    story: "Eiendomsinvestor med portefølje innen nærings- og boligeiendom. Den konkrete selskapsstrukturen hentes fra databasen." },
  { navn: "Terje Tinholt", fodselsaar: null, bransje: "Eiendom",
    story: "Eiendomsutvikler og investor i Oslo-området, kjent for bolig- og næringsprosjekter." },
  { navn: "Egil Stenshagen", fodselsaar: 1947, bransje: "Bil / eiendom / investering",
    story: "Investor med interesser i bilimport/-forhandling, eiendom og børsnoterte selskaper, bygd opp over flere tiår." },
  { navn: "Carl Erik Krefting", fodselsaar: null, bransje: "Eiendom",
    story: "Eiendomsinvestor via Carucel, kjent for utvikling av næringseiendom i Oslo. Bygde formue på kjøp, utvikling og salg av eiendom." },
  { navn: "Ståle Kyllingstad", fodselsaar: 1960, bransje: "Oljeservice / industri",
    story: "Bygde industrikonsernet IKM Gruppen innen olje- og gassrelaterte tjenester på Vestlandet. Klassisk industribygger fra oljeservice." },
  { navn: "Jakob Hatteland", fodselsaar: 1951, bransje: "Teknologi / logistikk / AutoStore",
    story: "Gründeren bak teknologimiljøet som utviklet AutoStore – det automatiserte lagersystemet med kuber og roboter som ble en global suksess og milliardbørsnotering. Bygde elektronikk- og teknologivirksomhet på Vestlandet." },
  { navn: "Ingvar Hognaland", fodselsaar: null, bransje: "Teknologi / AutoStore",
    story: "Sentral teknolog/oppfinner i miljøet bak AutoStore-systemet. Knyttet til kommersialiseringen av lagerrobot-teknologien." },
  { navn: "Bård Eker", fodselsaar: 1961, bransje: "Design / industri / teknologi",
    story: "Industridesigner og gründer bak Eker Design, med tunge bidrag til blant annet Hydrolift-båter og Koenigsegg-superbiler. Kombinerer design, industri og teknologi-investeringer." },
  { navn: "Geir Førre", fodselsaar: 1960, bransje: "Teknologi / halvleder",
    story: "Serieentreprenør innen halvledere; grunnla Chipcon (solgt til Texas Instruments) og senere Energy Micro (solgt til Silicon Labs). Reinvesterer i teknologiselskaper." },
  { navn: "Bjarne Skeie", fodselsaar: 1945, bransje: "Oljeservice / industri",
    story: "Industribygger fra Kristiansand innen oljeservice og boreteknologi (bl.a. National Oilwell-relatert virksomhet). Reinvesterte i teknologi og energi via Skeie-systemet." },
  { navn: "Atle Eide", fodselsaar: 1957, bransje: "Sjømat / industri / investering",
    story: "Sentral leder og eier i norsk oppdrettsnæring (bl.a. tidligere konsernsjef i Pan Fish/Marine Harvest-sfæren) og aktiv investor og styreprofil i sjømat og teknologi." },
  { navn: "Bjørn Risa", fodselsaar: null, bransje: "Anlegg / entreprenør",
    story: "Bygde entreprenør- og anleggskonsernet Risa på Jæren til en stor regional aktør innen vei, anlegg og masseforflytning." },
  { navn: "Olav Stangeland", fodselsaar: null, bransje: "Anlegg / eiendom",
    story: "Eier og leder av entreprenørkonsernet Stangeland Maskin på Jæren, en av Norges største maskinentreprenører, med tilhørende eiendom." },
  { navn: "Tor Dagfinn Veen", fodselsaar: null, bransje: "Bil / eiendom",
    story: "Investor med interesser i bilforhandlervirksomhet og eiendom, bygd opp over tid via familieeide selskaper." },
  { navn: "Atle Berge", fodselsaar: null, bransje: "Bygg / betong / industri",
    story: "Bygde industri- og byggkonsernet Ott ( Overhalla/ betongelement m.m.) med vekt på prefab og industriell produksjon." },
  { navn: "Ola Braanaas", fodselsaar: 1962, bransje: "Oppdrett / sjømat",
    story: "Grunnla og eier oppdrettsselskapet Firda Seafood i Sogn og Fjordane. Klassisk oppdrettsgründer som bygde lakseformue fra konsesjoner og produksjon." },
  { navn: "Helge Gåsø", fodselsaar: 1961, bransje: "Sjømat / shipping / oppdrett",
    story: "Trøndersk sjømat- og shippinginvestor (Frøy-systemet), med tyngde i oppdrettsservice-fartøy og oppdrett. Bygde formue på vekst i havbruksnæringen." },
  { navn: "Roger Hofseth", fodselsaar: 1968, bransje: "Sjømat / industri",
    story: "Eier av Hofseth-konsernet på Sunnmøre innen lakseforedling og sjømat, med ambisjoner innen bioteknologi og full utnyttelse av råstoff." },
  { navn: "Inge Berg", fodselsaar: 1958, bransje: "Oppdrett / sjømat",
    story: "Grunnla og eier oppdrettskonsernet Nordlaks i Vesterålen, en av Norges største familieeide lakseprodusenter, kjent for «Havfarm»-merdene til havs." },
  { navn: "Gustav Magnar Witzøe", fodselsaar: 1953, bransje: "Oppdrett / sjømat",
    story: "Grunnla SalMar og bygde det til en av verdens største lakseprodusenter fra Frøya i Trøndelag. Senior bak en av Norges største sjømatformuer (eierskapet er delvis overført til sønnen)." },
  { navn: "Frode Teigen", fodselsaar: null, bransje: "Sjømat / investering",
    story: "Investor med tunge posisjoner i sjømat (bl.a. oppdrett) og børsnoterte selskaper, samt eiendom. Aktiv eier via egne holdingselskaper." },
  { navn: "Trygve Seglem", fodselsaar: null, bransje: "Shipping / offshore",
    story: "Bygde rederiet Knutsen OAS Shipping i Haugesund, spesialisert på bøyelast- og gasstankskip (shuttle-tankere, LNG). Familieeid shipping-formue." },
  { navn: "Per Sævik", fodselsaar: 1940, bransje: "Shipping / offshore / ferge",
    story: "Bygde Havila-systemet på Sunnmøre innen offshore-fartøy, ferger og shipping. Familieeid maritimt konsern med dype røtter i fiskeri og rederidrift." },
  { navn: "Bjørn Tore Larsen", fodselsaar: 1968, bransje: "Luftfart / shipping / bemanning",
    story: "Gründer og sjef i el-flyselskapet Heart Aerospace og tidligere bygger av maritim bemanning/shipping. Satser på elektrifisering av kortbanefly." },
  { navn: "Bjørn Kjos", fodselsaar: 1946, bransje: "Luftfart",
    story: "Tidligere jagerflyger og advokat som grunnla og bygde lavprisflyselskapet Norwegian til Europas tredje største, med aggressiv vekst og langdistanse-satsing. Senere engasjert i droner og teknologi." },
  { navn: "Jørn Lyseggen", fodselsaar: 1968, bransje: "Teknologi / SaaS",
    story: "Grunnla medieovervåkings- og analyseselskapet Meltwater, bygd fra Norge til en global SaaS-aktør børsnotert i Oslo. Kjent også for filantropi (MEST i Afrika)." },
  { navn: "Jon von Tetzchner", fodselsaar: 1967, bransje: "Teknologi / nettleser",
    story: "Medgrunnlegger av nettleseren Opera og senere grunnlegger av personvern-nettleseren Vivaldi. Pioner i norsk programvare med global rekkevidde." },
  { navn: "Eilert Hanoa", fodselsaar: 1970, bransje: "Teknologi / software / edtech",
    story: "Bygde forretningssystem-selskapet Mamut (solgt til Visma) og er i dag sjef og eier i læringsplattformen Kahoot. Serieentreprenør og investor i norsk programvare." },
  { navn: "Johan Brand", fodselsaar: 1973, bransje: "Teknologi / edtech",
    story: "Medgrunnlegger av Kahoot, den globale spillbaserte læringsplattformen. Bygde edtech-suksess fra et norsk-britisk gründermiljø." },
  { navn: "Åsmund Furuseth", fodselsaar: null, bransje: "Teknologi / edtech",
    story: "Medgrunnlegger av Kahoot. Sentral i å bygge læringsplattformen til en global tjeneste med titalls millioner brukere." },
  { navn: "Morten Versvik", fodselsaar: null, bransje: "Teknologi / edtech",
    story: "Medgrunnlegger av Kahoot og del av gründerteamet bak den spillbaserte læringsplattformen." },
  { navn: "Alf Inge Wang", fodselsaar: 1970, bransje: "Teknologi / edtech",
    story: "Professor ved NTNU og medgrunnlegger av Kahoot; den akademiske opphavsmannen bak konseptet for spillbasert læring." },
  { navn: "Magnus Haug Wanberg", fodselsaar: 1991, bransje: "Teknologi / hardware",
    story: "Ung gründer bak teknologiselskaper innen blant annet 3D/hardware (Remarkable-sfæren), kjent for å bygge globale produkter fra Norge." },
  { navn: "Henrik Müller-Hansen", fodselsaar: null, bransje: "Teknologi / print / logistikk",
    story: "Grunnla e-handels-/print-on-demand-plattformen Gelato, bygd til en global aktør for distribuert produksjon og logistikk." },
  { navn: "Are Traasdahl", fodselsaar: 1975, bransje: "Teknologi / adtech / venture",
    story: "Serieentreprenør; grunnla mobil-adtech-selskapet Tapad (solgt til Telenor) og senere supply chain-selskapet Crisp i USA. Bygde formue på exits i teknologi." },
  { navn: "Rune Syversen", fodselsaar: null, bransje: "Teknologi / IT-tjenester",
    story: "Medgrunnlegger og leder av IT-konsulentkonsernet Crayon, en stor nordisk aktør innen programvare- og skyrådgivning." },
  { navn: "Jens Rugseth", fodselsaar: 1955, bransje: "Teknologi / IT / investering",
    story: "Serieentreprenør og investor i IT-tjenester; medgrunnlegger av blant annet Crayon og en rekke teknologiselskaper. Aktiv eier og styreprofil." },
  { navn: "Karl Munthe-Kaas", fodselsaar: 1983, bransje: "Netthandel / dagligvare / teknologi",
    story: "Medgrunnlegger og leder av netthandels-dagligvaren Oda (tidligere Kolonial.no), en av Norges mest kjente e-handelssatsinger innen mat." },
  { navn: "Dag Kittlaus", fodselsaar: 1967, bransje: "Teknologi / AI / software",
    story: "Norsk-amerikansk gründer som skapte taleassistenten Siri (solgt til Apple) og senere AI-selskapet Viv (solgt til Samsung). Pioner innen AI-assistenter." },
  { navn: "Tellef Thorleifsson", fodselsaar: 1966, bransje: "Venture / investering",
    story: "Medgrunnlegger av venturefondet Northzone, en av Nordens ledende tidligfase-investorer (bl.a. tidlig i Spotify). Senere leder av Norfund." },
  { navn: "Rune Arnhoff", fodselsaar: null, bransje: "Handel / industri",
    story: "Investor og eier med interesser i handel og industri, bygd opp via egne selskaper. Selskapsstrukturen hentes fra databasen." },
  { navn: "Terje Høili", fodselsaar: 1944, bransje: "Handel / retail",
    story: "Bygde formue på handel og varedistribusjon via egne selskaper, med tilhørende eiendom." },
  { navn: "Einar Øgrey Brandsdal", fodselsaar: 1983, bransje: "Netthandel / retail",
    story: "Gründer av netthandelsselskapet Brandsdal (bl.a. Cocopanda/ blivakker.no), bygd til en stor nordisk e-handelsaktør innen skjønnhet og forbruksvarer." },
  { navn: "Geir Hove", fodselsaar: null, bransje: "Restaurant / franchise",
    story: "Bygde restaurant- og franchisevirksomhet i Norge. Den konkrete selskapsstrukturen hentes fra databasen." },
  { navn: "Kristian Adolfsen", fodselsaar: 1961, bransje: "Helse / omsorg / hotell",
    story: "Sammen med broren Roger bygd Adolfsen-gruppen innen privat helse og omsorg (barnehager, sykehjem), hotell og eiendom – et stort, bredt familieeid konsern." },
  { navn: "Roger Adolfsen", fodselsaar: 1964, bransje: "Helse / omsorg / hotell",
    story: "Medbygger av Adolfsen-gruppen med broren Kristian, med tyngde i omsorg, barnehager, hotell og eiendom i Norden." },
  { navn: "Bjørn Maaseide", fodselsaar: 1968, bransje: "Trening / eiendom / investering",
    story: "Tidligere toppidrettsutøver (sandvolleyball) som bygde treningskjede (bl.a. via Family Sports Club-sfæren), eiendom og investeringer." },
  { navn: "Bjørn Dæhlie", fodselsaar: 1967, bransje: "Idrett / eiendom / investering",
    story: "Tidenes vinter-OL-vinner i langrenn som etter karrieren bygde formue på eiendom, klesmerke (Dæhlie) og investeringer." },
  { navn: "Erling Braut Haaland", fodselsaar: 2000, bransje: "Fotball / investering",
    story: "Verdensstjerne i fotball (Manchester City) med en av idrettens høyeste inntekter. Plasserer inntektene i eiendom og investeringer via egne selskaper." },
  { navn: "Martin Ødegaard", fodselsaar: 1998, bransje: "Fotball / investering",
    story: "Landslagskaptein og Premier League-spiller (Arsenal) som kanaliserer inntekter inn i investeringer og eiendom via egne selskaper." },
  { navn: "Viktor Hovland", fodselsaar: 1997, bransje: "Golf",
    story: "En av verdens beste golfspillere, med betydelige premie- og sponsorinntekter som forvaltes via egne selskaper." },
  { navn: "Casper Ruud", fodselsaar: 1998, bransje: "Tennis",
    story: "Norges fremste tennisspiller gjennom tidene, med premie- og sponsorinntekter på toppnivå, organisert via egne selskaper og tennisakademi." },
  { navn: "Aksel Lund Svindal", fodselsaar: 1982, bransje: "Idrett / investering",
    story: "Alpinlegende og dobbel OL-vinner som etter karrieren har bygd en portefølje av investeringer og styreverv i blant annet teknologi og merkevare." },
  { navn: "Magnus Carlsen", fodselsaar: 1990, bransje: "Sjakk / teknologi / investering",
    story: "Tidenes sjakkspiller og mangeårig verdensmester. Medeier i Play Magnus Group (sjakk-app, solgt til Chess.com) – en sjelden kommersialisering av sjakk til teknologiformue." },
  { navn: "Kyrre Gørvell-Dahll", fodselsaar: 1991, bransje: "Musikk / underholdning",
    story: "Verdenskjent DJ og produsent under artistnavnet Kygo. Bygde formue på musikk, turnévirksomhet og merkevaren Palm Tree (festival, klær, medier)." },
  { navn: "Alan Walker", fodselsaar: 1997, bransje: "Musikk / underholdning",
    story: "Global elektronisk artist (bl.a. «Faded») med enorme streamingtall, som har bygd formue på musikk, merch og digital tilstedeværelse." },
  { navn: "Jo Nesbø", fodselsaar: 1960, bransje: "Forfatter / media / investering",
    story: "Internasjonal bestselgerforfatter (Harry Hole-serien) med inntekter fra bøker, film og rettigheter, forvaltet via egne selskaper." },
  { navn: "Morten Harket", fodselsaar: 1959, bransje: "Musikk / underholdning",
    story: "Vokalist i a-ha, en av Norges mest suksessrike musikkeksporter gjennom tidene, med inntekter fra musikk og rettigheter." },
  { navn: "Magne Furuholmen", fodselsaar: 1962, bransje: "Musikk / kunst / investering",
    story: "Medlem av a-ha (låtskriver bak «Take On Me») og anerkjent billedkunstner. Inntekter fra musikk, kunst og rettigheter." },
  { navn: "Pål Waaktaar-Savoy", fodselsaar: 1961, bransje: "Musikk / underholdning",
    story: "Gitarist og hovedlåtskriver i a-ha, med varige inntekter fra et av verdens mest spilte popkataloger." },
  { navn: "Jan Thomas", fodselsaar: 1966, bransje: "Media / merkevare / skjønnhet",
    story: "Make-up-artist og TV-personlighet som har bygd en merkevare innen skjønnhetsprodukter og media rundt sitt eget navn." },
  { navn: "Silje Landevåg", fodselsaar: null, bransje: "Netthandel / retail",
    story: "Gründer innen netthandel/retail. Den konkrete selskapsstrukturen hentes fra databasen." },
  { navn: "Anita Schjøll Brede", fodselsaar: 1985, bransje: "Teknologi / AI",
    story: "Gründer av AI-selskapet Iris.ai, som bruker kunstig intelligens for å strukturere vitenskapelig forskning. Internasjonalt profilert teknologigründer." },
  { navn: "Christine Spiten", fodselsaar: 1990, bransje: "Teknologi / hardware / havteknologi",
    story: "Medgrunnlegger av Blueye Robotics, som lager undervannsdroner. Profilert innen havteknologi og kvinnelig entreprenørskap." },
  { navn: "Håkon Wium Lie", fodselsaar: 1965, bransje: "Teknologi / web",
    story: "Oppfinneren av CSS (Cascading Style Sheets), en grunnstein i moderne web. Lenge teknologidirektør i Opera; pioner i åpne web-standarder." },
  { navn: "Jan Grønbech", fodselsaar: null, bransje: "Teknologi / ledelse / investering",
    story: "Tidligere mangeårig Norgessjef i Google, senere aktiv som investor og styreprofil i teknologiselskaper." },
  { navn: "Morten Lund", fodselsaar: 1972, bransje: "Venture / investering",
    story: "Serieinvestor og gründer kjent for tidlige veddemål på teknologiselskaper (bl.a. Skype-miljøet), med både store gevinster og tap." },
  { navn: "Erik Haugane", fodselsaar: 1958, bransje: "Olje / energi",
    story: "Oljepioner som var med å bygge letevirksomheten Det norske oljeselskap (forløper til Aker BP) og senere nye energiselskaper. Kjent for å utfordre de store på norsk sokkel." },

  { navn: "Stein Erik Hagen", fodselsaar: 1956, bransje: "Dagligvare / investering",
    story: "Bygde lavpriskjeden RIMI og Hakon Gruppen, fusjonerte inn i ICA og samlet formuen i familieselskapet Canica. Stor eier i Orkla, og investeringer i blant annet handel, eiendom og e-handel (Komplett, Jernia)." },
  { navn: "Johan H. Andresen", fodselsaar: 1961, bransje: "Investering / industri",
    story: "Arvet og videreførte Tiedemanns-formuen (tobakk) og omdannet den til investeringsselskapet Ferd – aktiv eier, private equity, eiendom og sosialt entreprenørskap. Tidligere leder av Etikkrådet for Oljefondet." },
  { navn: "Christen Sveaas", fodselsaar: 1956, bransje: "Investering / finans",
    story: "Kontrollerer investeringsselskapet Kistefos, med interesser i industri, finans og skog. Aktiv og tydelig investor på Oslo Børs; også kjent kunstsamler bak Kistefos-museet." },
  { navn: "Trond Mohn", fodselsaar: 1943, bransje: "Industri / filantropi",
    story: "Bygde og solgte pumpeprodusenten Frank Mohn (Framo) i Bergen – en industriformue fra maritim pumpeteknologi. En av Norges største private givere til forskning og idrett." },
  { navn: "Kristian Siem", fodselsaar: 1949, bransje: "Shipping / offshore / investering",
    story: "Bygde Siem Industries med tyngde i offshore, shipping, oppdrett og industri. Klassisk syklisk investor som kjøper når andre selger; opererer fra utlandet med globale eierposter." },
  { navn: "Christian Ringnes", fodselsaar: 1954, bransje: "Eiendom",
    story: "Bygde eiendomskonsernene Eiendomsspar og Victoria Eiendom til tunge eiere av nærings- og hotelleiendom i Oslo. Også kjent kunstsamler og mannen bak skulpturparken på Ekeberg." },
  { navn: "Anette S. Olsen", fodselsaar: 1956, bransje: "Shipping / energi / eiendom",
    story: "Leder og hovedeier i Fred. Olsen-systemet (Bonheur m.fl.) med interesser i fornybar energi (vind), offshore, cruise og eiendom – en av Norges eldste og bredeste familieformuer." },
  { navn: "Celina Midelfart", fodselsaar: 1972, bransje: "Investering / eiendom",
    story: "Viderefører og bygde ut Midelfart-formuen (opprinnelig kosmetikk/forbruksvarer) via Midelfart Capital, med investeringer i eiendom, helse og vekstselskaper." },
  { navn: "Katharina Andresen", fodselsaar: 1995, bransje: "Investering (arving)",
    story: "Medeier i familieselskapet Ferd sammen med søsteren, etter overføring fra faren Johan H. Andresen. En av Norges yngste storformuer, knyttet til Tiedemanns-arven." },
  { navn: "Alexandra Andresen", fodselsaar: 1996, bransje: "Investering (arving)",
    story: "Medeier i Ferd sammen med søsteren Katharina. Tidligere internasjonal topprytter; formuen er knyttet til familiens eierskap i investeringsselskapet Ferd." },
  { navn: "Per Grieg", fodselsaar: null, bransje: "Sjømat / shipping",
    story: "Sentral i Grieg-gruppen i Bergen, med virksomhet innen oppdrett (Grieg Seafood), shipping (Grieg Star) og logistikk – en bred maritim familieformue." },
  { navn: "Petter Varner", fodselsaar: null, bransje: "Retail / klær",
    story: "Del av familien bak Varner-gruppen (Dressmann, Cubus, Bik Bok, Carlings m.fl.), en av Nordens største motekjedekonsern, bygd av faren Frank Varner." },
  { navn: "Johan Johannson", fodselsaar: null, bransje: "Dagligvare",
    story: "Hovedeier i NorgesGruppen (Kiwi, Meny, Spar) via familieselskapet Joh. Johannson – Norges største dagligvarekonsern, med tilhørende eiendom og engros." },
  { navn: "Peder Smedvig", fodselsaar: null, bransje: "Shipping / energi / eiendom",
    story: "Viderefører Smedvig-formuen fra Stavanger, opprinnelig bygd på shipping og oljerigger (Smedvig Offshore), nå investeringer i eiendom, energi og finans." },
  { navn: "Knut Ugland", fodselsaar: null, bransje: "Shipping",
    story: "Del av Ugland-familien (J.J. Ugland) fra Grimstad, en av Norges eldste rederifamilier med virksomhet innen shipping, offshore og industri." },
  { navn: "Morten Høegh", fodselsaar: null, bransje: "Shipping",
    story: "Del av Höegh-familien (Leif Höegh & Co), med tyngde i bilfrakt (Höegh Autoliners) og gass (Höegh LNG) – en klassisk norsk shippingformue." },
  { navn: "Christen Sundt", fodselsaar: null, bransje: "Investering",
    story: "Viderefører Sundt-formuen via investeringsselskapet Sundt AS, med brede finansielle investeringer i børsnoterte selskaper og industri." },
  { navn: "Endre Røsjø", fodselsaar: null, bransje: "Eiendom / investering",
    story: "Eiendoms- og finansinvestor med base i Oslo, kjent for nærings­eiendom og langsiktige investeringer via egne selskaper." },
  { navn: "Runar Vatne", fodselsaar: null, bransje: "Eiendom",
    story: "Bygde eiendomsformue via Vatne Property med en stor portefølje av nærings- og handelseiendom, særlig i Oslo-området." },
  { navn: "Ola Mæle", fodselsaar: null, bransje: "Investering / eiendom",
    story: "Investor og eiendomsutvikler med bred portefølje innen eiendom, finans og industri, bygd opp via egne selskaper." },
  { navn: "Espen Galtung Døsvig", fodselsaar: null, bransje: "Eiendom / investering",
    story: "Bergensbasert investor og eiendomsutvikler med interesser i eiendom og børsnoterte selskaper." },
  { navn: "Jan Petter Sissener", fodselsaar: null, bransje: "Finans / forvaltning",
    story: "Profilert forvalter og investor; grunnla Sissener AS og hedgefondet Sissener Canopus. Kjent markedskommentator med lang fartstid i norsk finans." },
  { navn: "Helge Møgster", fodselsaar: null, bransje: "Sjømat / offshore",
    story: "Sentral i Møgster-familien fra Austevoll, med eierskap i Austevoll Seafood (Lerøy/Pelagia) og offshore (DOF) via Laco – en av Norges største sjømat- og maritime formuer." },
  { navn: "Idar Vollvik", fodselsaar: null, bransje: "Telecom / gründer",
    story: "Gründer som bygde mobilselskapet Chess og solgte det til Telenor, og har siden drevet en rekke nye satsinger. Kjent for rask oppbygging og høyt tempo." },
  { navn: "Olav Thon", fodselsaar: 1923, bransje: "Eiendom / hotell",
    story: "Norges mest kjente eiendomskonge (1923–2024). Bygde Olav Thon Gruppen og Thon Hotels fra skinnhandel til et av landets største eiendoms- og hotellimperier. Ga formuen til Olav Thon Stiftelsen." },
];
